---

- name: create user luc
  user:
    name: luc
    groups: adm,sudo
    createhome: yes
    generate_ssh_key: yes
  sudo: yes

- name: copy github key
  copy:
    src: ~/.ssh/id_rsa_pi_github
    dest: ~luc/.ssh/
    owner: luc
    group: luc
    mode: 0600
  sudo: yes

- name: copy git config
  copy:
    src: ../config/ssh/config
    dest: ~luc/.ssh/config
    owner: luc
    group: luc
  sudo: yes

- name: install pi user public key
  lineinfile:
    line: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    dest: ~luc/.ssh/authorized_keys
    create: yes
    owner: luc
    group: luc
  sudo: yes
