---

- hosts: local
  roles:
    - local_clean

- hosts: tinc_gateway
  roles:
    - tinc_check

- hosts: gateway
  roles:
    - git_check

- hosts: gateway
  roles:
    - aptget_init

- hosts: tinc_gateway
  roles:
    - tinc_fetch_gateway

- hosts: gateway
  roles:
    - tinc_config

- hosts: tinc_gateway
  roles:
    - tinc_push_hosts

- hosts: gateway
  roles:
    - tinc_run

- hosts: gateway
  roles:
    - network_config
    - dhcp_config
    - user_creation
    - aptget_user

