---

- hosts: local
  roles:
    - local_clean

- hosts: tinc_gateway
  roles:
    - tinc_check

#- hosts: nodes 
#  roles:
#    - aptget_init

- hosts: tinc_gateway
  roles:
    - tinc_fetch_gateway

- hosts: nodes
  roles:
    - tinc_config

- hosts: tinc_gateway
  roles:
    - tinc_push_hosts

- hosts: nodes
  roles:
    - tinc_run

#- hosts: nodes
#  roles:
#    - network_config
#    - user_creation

